### ISSUE TITLE
Picure does not print in PDF if the size exceed the silde

### ISSUE THREAD

**Issue by albert-ying** [jhelvy/renderthis#44]
Here is a minimal example. It applies to any picture as far as I am aware of. This is a problem especially when using pictures with large white margins, It is hard to tell whether it exceeds the edge of the slide by eye.

```
---
title: 'cat'
subtitle: ''
author: ''
date:  ''
output:
  xaringan::moon_reader:
    lib_dir: libs
    self-contain: true
    nature:
      highlightStyle: github
      slideNumberFormat: ''
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

# Normal size cat

<img src="p1.png" width="57%" class="center" align=""/>

---

# Large cat

<img src="p1.png" width="100%" class="center" align=""/>
```

# Result HTML from `bulid_html`
<img width="1824" alt="image" src="https://user-images.githubusercontent.com/59846322/146037167-08506941-fea5-4a20-aac7-be77fc1d8f3a.png">
<img width="1823" alt="image" src="https://user-images.githubusercontent.com/59846322/146037181-bcc5a81b-5e32-4f75-a8d3-1c847af732cc.png">

# Result PDF from `bulid_pdf`

<img width="411" alt="image" src="https://user-images.githubusercontent.com/59846322/146037298-ede0d382-87bf-4fb1-90db-0d355581f7ef.png">
