### ISSUE TITLE
Error in onRejected(reason) : code: -32000   message: Browser window not found

### ISSUE THREAD

**Issue by privefl** [jhelvy/renderthis#77]
`renderthis::to_pdf()` used to work fine, now I get this error a few months ago, I don't know why.

**Comment by privefl** [comment]
When I use `partial_slides = FALSE`, I get another error:
```
Error in force(expr) : 
  Failed to generate output. Reason: Failed to open http://127.0.0.1:4921/favicon.ico (HTTP status code: 404)
```

**Comment by jhelvy** [comment]
I also am getting this, it recently emerged. I don't think we changed anything to the package, so my guess is something changed in a dependency.

**Comment by privefl** [comment]
For the first error, I tried to change my default web browser to either Edge/Chrome/Firefox, 
But that didn't help.

**Comment by robert-cope** [comment]
I've also encountered this favico.ico error this week (late August 2024), on documents that converted successfully last week, and I haven't been able to work out what changed. I can make the `renderthis::to_pdf()` conversion work if I add the following html to the header:
`<link rel="shortcut icon" href="#" />`
(which I believe means it won't look for a favicon.ico)

In practice I do this in the yaml of a Qmd source like:
```
format: 
  revealjs:
    include-in-header:
      - text: <link rel="shortcut icon" href="#" />
 ```

**Comment by privefl** [comment]
I tried to put this `<link     />` in an HTML file and use
```yaml
output:
  xaringan::moon_reader:
    includes:
      in_header: "no_favicon.html"
```
But it does not change anything; am I doing anything wrong here?
